### ISSUE TITLE
dhcpcd: no valid interfaces found

### ISSUE THREAD

**Issue by git-bruh** [illiliti/libudev-zero#18]
When `dhcpcd` is started by the runit (`busybox` init) service, it says `no valid interfaces found` and just stops there, the service has to be restarted manually for it to detect my wifi adapter, but this is not the case with `eudev`:

```
no such user dhcpcd
dhcpcd-9.4.0 starting
dev: loaded udev
DUID 00:01:00:01:27:5e:0a:a4:d0:39:42:49:f3:14
no valid interfaces found
no interfaces have a carrier
```

I'm not sure if this is directly related to `libudev-zero`, but might be related to `dhcpcd` starting before `mdev` is initialised, any ideas ?

**Comment by illiliti** [comment]
> might be related to `dhcpcd` starting before `mdev` is initialised

This. Technically, libudev-zero should signal dhcpcd about new devices via hotplugging. Ensure that you have properly working hotplugging support.

There is also a possibility of race condition between dhcpcd and mdev which can lead to impossibility to detect net devices due to permission issues. Try to run dhcpcd as root or implement proper synchronization to mdev.

**Comment by git-bruh** [comment]
Hmm, hotplugging seems to be working fine, `dhcpcd` is running as root.

> implement proper synchronization to mdev

How does one go about this ?

**Comment by illiliti** [comment]
> How does one go about this ?

Ah, sorry I forgot about that dhcpcd should be always run as root. You don't need it. This synchronization is needed for e.g. root-less Xorg which is usually(or rarely, it depends on init implementation) fails to initialize drm devices at startup due to access rights. I'll probably add some docs about it to readme.

Does the dhcpcd working if compiled without udev support?

**Comment by git-bruh** [comment]
Just compiled it without udev support, works great now.

**Comment by git-bruh** [comment]
@illiliti Do you plan to tackle this in `libudev-zero` ? If not, I'll close the issue.

**Comment by illiliti** [comment]
Yes, I'll investigate this further later

**Comment by git-bruh** [comment]
Yeah it stopped happening for me, maybe it was an issue with my old config
